Repository liquibase/liquibase-test-harness, pull requests merged in 2023-10, with the labels that each got.

#608 addDefaultValueBoolean expected sql updated
  src/main/resources/liquibase/harness/change/expectedSql/db2-luw/addDefaultValueBoolean.sql
Labels: TypeBug

#632 DAT-16122
  .github/workflows/main.yml
Labels: TypeBug, skipReleaseNotes

#634 DAT-16122
  .github/workflows/main.yml
Labels: TypeBug, skipReleaseNotes

#638 remove env GITHUB_TOKEN
  .github/workflows/main.yml
Labels: skipReleaseNotes
