Repository liquibase/liquibase-test-harness, pull requests merged in 2024-02, with the labels that each got.

#731 made fixes in expected snapshots for mariadb boolean tests
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/addDefaultValueBoolean.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/addNotNullConstraintBitBoolean.json
Labels: TypeTest

#733 DAT-16820. refactored cloud DBs init-scripts to follow Liquibase atomic changes best practice
  src/test/resources/init-changelogs/aws/mariadb.sql
  src/test/resources/init-changelogs/aws/mssql.sql
  src/test/resources/init-changelogs/aws/mysql.sql
  src/test/resources/init-changelogs/aws/postgresql.sql
  src/test/resources/init-changelogs/azure/mysql.sql
  src/test/resources/init-changelogs/azure/postgresql.sql
  src/test/resources/init-changelogs/azure/sqlserver.sql
  src/test/resources/init-changelogs/gcp/mssql.sql
  src/test/resources/init-changelogs/gcp/mysql.sql
  src/test/resources/init-changelogs/snowflake/snowflake.sql
Labels: TypeEnhancement

#729 DAT-16491 : get liquibase-core working with develop branch
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/addDefaultValueBoolean.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/addNotNullConstraintBitBoolean.json
  src/main/resources/liquibase/harness/change/expectedSql/mariadb/addDefaultValueBoolean.sql
  src/main/resources/liquibase/harness/change/expectedSql/mariadb/addNotNullConstraintBitBoolean.sql
  src/test/resources/init-changelogs/aws/mysql.sql
Labels: skipReleaseNotes

#737 DAT-16491: authorize setup fix
  .github/workflows/main.yml
Labels: skipReleaseNotes
