Repository liquibase/liquibase-test-harness, pull requests merged in 2024-01, with the labels that each got.

#712 fix aws mariadb tests
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createFunction.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackage.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackageBody.json
Labels: skipReleaseNotes, TypeTest

#622 DAT-1565 Investigate LocalStack for automated testing of AWS Platforms
  .github/workflows/aws.yml
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createFunction.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackage.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackageBody.json
  src/test/resources/init-changelogs/aws/mysql.sql
Labels: TypeEnhancement, skipReleaseNotes

#719 Update README.md to include Windows syntax
  README.md
Labels: TypeEnhancement

#723 added separate init script for MySQL GCP
  .github/workflows/gcp.yml
  src/test/resources/init-changelogs/gcp/mysql.sql
Labels: skipReleaseNotes

#727 Expected SQL files updated to reflect MariaDB boolean changes from OSS
  src/main/resources/liquibase/harness/change/expectedSql/mariadb/addDefaultValueBoolean.sql
  src/main/resources/liquibase/harness/change/expectedSql/mariadb/addNotNullConstraintBitBoolean.sql
Labels: TypeEnhancement
