Repository liquibase/liquibase-test-harness, pull requests merged in 2024-03, with the labels that each got.

#747 DAT-15025. added postges 16 to the test-harness test suite
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/16/createView.json
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/16/createView.sql
  src/main/resources/liquibase/harness/snapshot/expectedSnapshot/postgresql/16/createView.json
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: TypeEnhancement, DBPostgres, TypeTest

#748 DAT-17032-17033 Setup Azure Postgres 15/16
  .github/workflows/azure.yml
Labels: skipReleaseNotes, sdou

#755 DAT-17264: use build-logic reusable workflow
  .github/workflows/attach-artifact-release.yml
  .github/workflows/create-release.yml
  .github/workflows/release-published.yml
Labels: TypeEnhancement, skipReleaseNotes
