Repository liquibase/liquibase-test-harness, pull requests merged in 2024-04, with the labels that each got.

#768 [DAT-17352] Fix Attach Artifact to Release workflow
  .github/workflows/attach-artifact-release.yml
  .github/workflows/create-release.yml
Labels: TypeBug

#770 [DAT-17352] Fix workflow
  .github/workflows/create-release.yml
Labels: TypeBug

#771 [DAT-17352] Trigger workflow
  .github/workflows/create-release.yml
Labels: TypeBug, skipReleaseNotes

#773 [DAT-17352] Bring configuration from parent pom
  pom.xml
Labels: TypeBug

#774 [DAT-17352] Add copy-rename-maven-plugin plugin
  pom.xml
Labels: TypeBug

#784 Downgrade MSSQL driver version from 12.7.0.jre11-preview to 12.6.1.jre11
  pom.xml
Labels: sdou

#791 [DAT-16959, DAT-16960] updated support matrix
  README.md
Labels: documentation, TypeEnhancement, runTestHarnessTests
