Repository liquibase/liquibase-test-harness, pull requests merged in 2024-05, with the labels that each got.

#806 fix mssql localstack issue
  .github/workflows/aws.yml
Labels: TypeTest

#808 DAT-17572 Modify CI/CD Configurations for Nexus Integration
  .github/workflows/OracleRunParallel.yml
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.edb.yml
  src/test/resources/docker/oracle-artifactory/docker-compose.yml
Labels: sdou

#810 DAT-17492: remove user status check
  .github/workflows/main.yml
Labels: TypeBug, skipReleaseNotes
