Repository liquibase/liquibase-test-harness, pull requests merged in 2024-08, with the labels that each got.

#854 using 2019-CU27-ubuntu-20.04 version of mssql instead of the latest
  src/test/resources/docker/docker-compose.yml
Labels: TypeEnhancement

#860 adding logs
  src/main/groovy/liquibase/harness/diff/DiffCommandTestHelper.groovy
  src/main/resources/liquibase/harness/diff/diffDatabases.yml
Labels: skipReleaseNotes

#861 DAT-18391. Fixing test-harness failures
  src/main/resources/liquibase/harness/diff/diffDatabases.yml
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/cockroachdb/column.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/cockroachdb/createIndex.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/cockroachdb/createTable.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/cockroachdb/primary.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/cockroachdb/unique.sql
Labels: TypeTest

#874 [no-jira] removed release-drafter workflow
  .github/workflows/release-drafter.yml
Labels: skipReleaseNotes

#875 allow create-release to trigger manually to rebuild release notes
  .github/workflows/create-release.yml
Labels: skipReleaseNotes

#876 fixed Advanced test for edb 16
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/10/createProcedure.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/10/createTrigger.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/11/createTrigger.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/16/createView.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.5/createProcedure.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.5/createSequence.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.5/createTrigger.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.6/createProcedure.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.6/createSequence.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/edb-edb/9.6/createTrigger.sql
  src/main/resources/liquibase/harness/snapshot/expectedSnapshot/edb-edb/16/createView.json
  src/main/resources/liquibase/harness/snapshot/expectedSnapshot/edb-edb/9.5/createSequence.json
  src/main/resources/liquibase/harness/snapshot/expectedSnapshot/edb-edb/9.6/createSequence.json
Labels: TypeTest

#877 Update README.md
  README.md
Labels: skipReleaseNotes

#885 🔧 DAT-18287: fix `Bad credentials`
  .github/workflows/main.yml
Labels: skipReleaseNotes

#886 Update main.yml
  .github/workflows/main.yml
Labels: skipReleaseNotes

#888 🔧 DAT-18287 statuses: write
  .github/workflows/main.yml
Labels: skipReleaseNotes
