Repository liquibase/liquibase-test-harness, pull requests merged in 2024-11, with the labels that each got.

#914 disable analytics (DAT-18903)
  pom.xml
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy
Labels: TypeEnhancement

#916 DAT-18864. testing titan issue fix
  .github/workflows/main.yml
Labels: TypeBug

#925 [DAT-19026] allowed to override Foundational test input files
  README.extensions.md
  README.md
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTestHelper.groovy
  src/main/groovy/liquibase/harness/util/FileUtils.groovy
  src/main/resources/liquibase/harness/compatibility/foundational/changelogs/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/changelogs/createTable.sql
  src/main/resources/liquibase/harness/compatibility/foundational/changelogs/createTable.yml
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/cockroachdb/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/db2-z/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/edb-edb/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/edb-postgres/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/edb/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/mssql/azure/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/mysql/azure/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/postgresql/azure/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/postgresql/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/postgresql/flexible/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/snowflake/createTable.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/sqlite/createTable.json
Labels: TypeEnhancement, TypeTest
