Repository liquibase/liquibase-test-harness, pull requests merged in 2024-07, with the labels that each got.

#833 [DAT-17590] Fix tests for 3.16.0 driver version
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addColumn.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addForeignKey.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addLookupTable.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addNotNullConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addPrimaryKey.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/addUniqueConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createTable.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createTableDataTypeDoubleIsFloat.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createTableDataTypeText.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createTableTimestamp.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/createView.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropAllForeignKeyConstraints.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropColumn.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropDefaultValue.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropForeignKey.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropFunction.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropNotNullConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropPrimaryKey.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropTable.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropUniqueConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropView.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/mergeColumns.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/modifyDataType.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/modifySql.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/renameColumn.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/renameSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/renameTable.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/renameView.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/setColumnRemarks.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/setTableRemarks.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/sql.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/sqlFile.sql
  src/main/resources/liquibase/harness/change/expectedSql/snowflake/valueSequenceNext.sql
  src/main/resources/liquibase/harness/data/expectedSql/snowflake/delete.sql
  src/main/resources/liquibase/harness/data/expectedSql/snowflake/insert.sql
  src/main/resources/liquibase/harness/data/expectedSql/snowflake/loadData.sql
Labels: TypeBug

#829 [DAT-17418] Update groovy and spock versions
  pom.xml
  src/main/groovy/liquibase/harness/AdvancedHarnessSuite.groovy
  src/main/groovy/liquibase/harness/BaseHarnessSuite.groovy
  src/main/groovy/liquibase/harness/FoundationalHarnessSuite.groovy
  src/main/groovy/liquibase/harness/change/ChangeObjectTests.groovy
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy
  src/main/groovy/liquibase/harness/data/ChangeDataTests.groovy
  src/main/groovy/liquibase/harness/generateChangelog/GenerateChangelogTest.groovy
  src/main/groovy/liquibase/harness/util/TestUtils.groovy
Labels: TypeEnhancement

#842 [DAT-16272] added edb 15
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  README.md
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.edb.yml
  src/test/resources/docker/teardown-infra.sh
  src/test/resources/harness-config.yml
Labels: TypeEnhancement

#845 testing previos version of 2022 image
  src/test/resources/docker/docker-compose.yml
Labels: TypeTest
