Repository liquibase/liquibase-test-harness, pull requests merged in 2024-12, with the labels that each got.

#932 fix: add "as BIGINT" by default to DB2luw, hsqldb and mssql sequences
  src/main/resources/liquibase/harness/change/expectedSql/db2-luw/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/db2-luw/createSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/db2-luw/dropSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/hsqldb/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/hsqldb/createSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/hsqldb/dropSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/mssql/alterSequence.sql
  src/main/resources/liquibase/harness/data/expectedSql/hsqldb/alterSequence.sql
Labels: TypeBug

#938 chore: remove MSSQL 2019 and 2022 from build until they are fixed.
  .github/workflows/main.yml
Labels: skipReleaseNotes

#939 chore: remove MSSQL 2019 and 2022 from build until they are fixed.
  .github/workflows/main.yml
Labels: skipReleaseNotes

#935 [DAT-19146] WalMart POC :: Informix :: Test :: Determine status of Informix integration functionality
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueComputed.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueDate.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueNumeric.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/alterSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createFunction.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createPackage.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createPackageBody.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedure.txt
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedure.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedureFromFile.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createTrigger.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropDefaultValue.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropProcedure.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropTrigger.xml
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValue.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValueBoolean.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValueNumeric.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/alterSequence.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/createTableTimestamp.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/createView.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/dropDefaultValue.json
  src/main/resources/liquibase/harness/change/expectedSql/informix/addCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueComputed.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueDate.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueSequenceNext.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addUniqueConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createFunction.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createPackage.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createPackageBody.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createProcedure.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createProcedureFromFile.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/disableCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/disableTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropFunction.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/enableCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/enableTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameView.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/setColumnRemarks.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/setTableRemarks.sql
  src/main/resources/liquibase/harness/data/changelogs/informix/loadUpdateData.csv
  src/main/resources/liquibase/harness/data/changelogs/informix/loadUpdateData.xml
  src/test/resources/docker/docker-compose.yml
  src/test/resources/docker/informix-init.sql
Labels: TypeTest

#933 DAT-19145 Basic template to setup Informix
  .github/workflows/main.yml
  pom.xml
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueComputed.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueDate.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/addDefaultValueNumeric.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/alterSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createFunction.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createPackage.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createPackageBody.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedure.txt
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedure.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createProcedureFromFile.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/createTrigger.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropDefaultValue.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropProcedure.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropSequence.xml
  src/main/resources/liquibase/harness/change/changelogs/informix/dropTrigger.xml
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValue.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValueBoolean.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/addDefaultValueNumeric.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/alterSequence.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/createTableTimestamp.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/createView.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/informix/dropDefaultValue.json
  src/main/resources/liquibase/harness/change/expectedSql/informix/addCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueComputed.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueDate.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addDefaultValueSequenceNext.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/addUniqueConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createFunction.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createPackage.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createPackageBody.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createProcedure.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createProcedureFromFile.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/createTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/disableCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/disableTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropFunction.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/dropTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/enableCheckConstraint.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/enableTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameTrigger.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/renameView.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/setColumnRemarks.sql
  src/main/resources/liquibase/harness/change/expectedSql/informix/setTableRemarks.sql
  src/main/resources/liquibase/harness/data/changelogs/informix/loadUpdateData.csv
  src/main/resources/liquibase/harness/data/changelogs/informix/loadUpdateData.xml
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/docker/informix-init.sql
  src/test/resources/harness-config.yml
Labels: TypeEnhancement

#942 [no-jira] brought @vladimirevd fix
  src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy
Labels: TypeBug

#945 fixing main after changes in core
  src/test/resources/H2/lbcat.mv.db
  src/test/resources/derby/lbcat/db.lck
  src/test/resources/derby/lbcat/log/log.ctrl
  src/test/resources/derby/lbcat/log/log5.dat
  src/test/resources/derby/lbcat/log/logmirror.ctrl
  src/test/resources/derby/lbcat/seg0/c10.dat
  src/test/resources/derby/lbcat/seg0/c230.dat
  src/test/resources/derby/lbcat/seg0/c241.dat
  src/test/resources/derby/lbcat/seg0/c251.dat
  src/test/resources/derby/lbcat/seg0/c4c0.dat
  src/test/resources/derby/lbcat/seg0/c90.dat
  src/test/resources/derby/lbcat/seg0/ca1.dat
  src/test/resources/derby/lbcat/seg0/cb1.dat
  src/test/resources/docker/percona-xtradb-cluster-init.sql
Labels: TypeEnhancement

#946 DAT-18731 - Resolving the /null problem when not finding the createTable.sql
  src/main/groovy/liquibase/harness/generateChangelog/GenerateChangelogTest.groovy
Labels: TypeBug

#947 DAT-14344. added initial setup for percona-mysql-8.4
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/changelogs/percona-xtradb-cluster/8.4/createFunction.xml
  src/main/resources/liquibase/harness/change/changelogs/percona-xtradb-cluster/8.4/dropFunction.xml
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: notableChanges
