Repository liquibase/liquibase-test-harness, pull requests merged in 2025-03, with the labels that each got.

#1009 DAT-19706. update junit & junit platform versions
  pom.xml
Labels: skipReleaseNotes

#1011 [no_jira] updated extension version and mysql driver
  pom.xml
Labels: sdou

#1012 [no_jira] Update pom.xml to get rid of open range version for core
  pom.xml
Labels: skipReleaseNotes

#1019 DAT-19773: removed cloud config for SingleServer Azure PostgreSQL
  .github/workflows/azure.yml
  README.md
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/azure/createTrigger.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/azure/disableTrigger.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/azure/dropFunction.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/azure/enableTrigger.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/azure/renameTrigger.json
  src/main/resources/liquibase/harness/compatibility/foundational/expectedResultSet/postgresql/azure/createTable.json
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/addCheckConstraint.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/addColumn.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/addForeignKey.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/addPrimaryKey.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/addUniqueConstraint.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createFunction.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createIndex.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createProcedure.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createSequence.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createTable.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createTrigger.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/azure/createView.sql
  src/test/resources/harness-config-cloud.yml
Labels: TypeEnhancement

#1020 Update README.md
  README.md
Labels: skipReleaseNotes
