Repository liquibase/liquibase-test-harness, pull requests merged in 2025-02, with the labels that each got.

#988 fixed mariadb 11.4 test failure
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/mariadb/11.4/createFunction.sql
Labels: skipReleaseNotes

#996 DAT-19653 DevOps :: Fix firebird and hsqldb infra
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  README.md
  README.non-docker-test-environments.md
  src/test/groovy/liquibase/harness/config/TestConfigTest.groovy
  src/test/resources/automation-runner.sh
  src/test/resources/docker/Dockerfiles/hsqldb/Dockerfile
  src/test/resources/docker/Dockerfiles/hsqldb/init.sql
  src/test/resources/docker/Dockerfiles/hsqldb/start.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/docker/teardown-infra.sh
  src/test/resources/harness-config.yml
  src/test/resources/self/test-config.yml
  src/test/resources/titan-installer.sh
Labels: sdou

#990 Fix for postgres
  src/main/resources/liquibase/harness/change/expectedSql/postgresql/addNotNullConstraintBitBoolean.sql
Labels: TypeTest

#1002 Revert "Fix for postgres"
  src/main/resources/liquibase/harness/change/expectedSql/postgresql/addNotNullConstraintBitBoolean.sql
Labels: skipReleaseNotes
