Repository liquibase/liquibase-test-harness, pull requests merged in 2025-01, with the labels that each got.

#952 [DAT-18428] Fixing issue with GCP_MSSQL
  .github/workflows/gcp.yml
  src/test/resources/init-changelogs/gcp/mssql.sql
Labels: TypeTest

#953 Fixing aws mssql
  .github/workflows/aws-weekly.yml
  .github/workflows/aws.yml
  src/main/resources/liquibase/harness/change/expectedSql/mssql/aws_2019/alterSequence.sql
  src/test/resources/harness-config-cloud.yml
Labels: TypeTest

#955 fixing aws_mssql
  .github/workflows/aws-weekly.yml
  .github/workflows/aws.yml
Labels: TypeTest

#956 Fixing cloud dbs
  src/main/resources/liquibase/harness/change/expectedSql/mssql/azure/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/mssql/gcp/alterSequence.sql
Labels: TypeTest

#959 Fixing cloud dbs
  src/main/resources/liquibase/harness/change/expectedSql/mssql/mi/alterSequence.sql
Labels: TypeTest

#948 DAT-19185. added mssql-2019 & 2022 back to the workflow
  .github/workflows/main.yml
Labels: skipReleaseNotes

#960 DAT-18891. added postgres 17 on prem support
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/17/createView.json
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/postgresql/17/createView.sql
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: notableChanges

#961 [DAT-18992] 2025 :: Q1 :: Interop :: MySQL 8.4 on-prem support
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/changelogs/mysql/8.4/createFunction.xml
  src/main/resources/liquibase/harness/change/changelogs/mysql/8.4/createPackage.xml
  src/main/resources/liquibase/harness/change/changelogs/mysql/8.4/createPackageBody.xml
  src/main/resources/liquibase/harness/change/changelogs/mysql/8.4/dropFunction.xml
  src/main/resources/liquibase/harness/change/expectedSnapshot/mysql/8.4/createFunction.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mysql/8.4/createPackage.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mysql/8.4/createPackageBody.json
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: TypeTest

#962 fixed advanced test failure for postgres 17
  src/main/resources/liquibase/harness/snapshot/expectedSnapshot/postgresql/17/createView.json
Labels: skipReleaseNotes

#963 DAT-19367 4.31.0 -- revert deploymentID DBCL/H changes
  src/test/resources/docker/percona-xtradb-cluster-init.sql
Labels: skipReleaseNotes

#966 Fixing mysql 8.4 advanced tests
  src/main/resources/liquibase/harness/generateChangelog/expectedChangeLog/mysql/8.4/addForeignKeyConstraint.xml
  src/main/resources/liquibase/harness/generateChangelog/expectedChangeLog/mysql/8.4/createFunction.xml
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/mysql/8.4/addForeignKeyConstraint.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/mysql/8.4/createFunction.sql
Labels: TypeTest

#967 Fixing gcpMSSQL
  .github/workflows/gcp.yml
Labels: TypeTest

#972 DAT-19350 configure test-harness to deploy master-snapshot to GPM
  .github/workflows/deploy-snapshot.yml
  pom.xml
Labels: sdou, skipReleaseNotes

#975 DAT-19303 DevOps :: TiDB :: Add ability to run custom SQL script that creates tables and table data against created db
  src/test/resources/docker/docker-compose.yml
  src/test/resources/docker/tidb-init.sql
Labels: sdou

#978 DAT-19442. fixed failures in sequences after the changes in the lates…
  src/main/resources/liquibase/harness/change/expectedSql/mssql/aws_2019/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/mssql/azure/alterSequence.sql
  src/main/resources/liquibase/harness/change/expectedSql/mssql/mi/alterSequence.sql
  src/main/resources/liquibase/harness/generateChangelog/expectedSql/db2-luw/createSequence.sql
Labels: skipReleaseNotes

#979 fixed mssql gcp failure
  src/main/resources/liquibase/harness/change/expectedSql/mssql/gcp/alterSequence.sql
Labels: skipReleaseNotes

#980 [DAT-12908] GenerateChangelogTest: add verification that 'objects' directory is created for stored logic objects.
  src/main/groovy/liquibase/harness/generateChangelog/GenerateChangelogTest.groovy
  src/main/groovy/liquibase/harness/generateChangelog/GenerateChangelogTestHelper.groovy
  src/main/groovy/liquibase/harness/util/TestUtils.groovy
Labels: TypeTest

#977 DAT-16963. added mariadb 11.4 support
  .github/workflows/advanced.yml
  .github/workflows/main.yml
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/11.4/createFunction.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/11.4/createPackage.json
  src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/11.4/createPackageBody.json
  src/test/resources/automation-runner.sh
  src/test/resources/docker/create-infra.sh
  src/test/resources/docker/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: TypeTest

#983 [DAT-18736] added common 'ignore testcase' functionality to Snapshot test
  .gitignore
  src/main/groovy/liquibase/harness/snapshot/SnapshotObjectTestHelper.groovy
  src/main/groovy/liquibase/harness/snapshot/SnapshotObjectTests.groovy
Labels: TypeEnhancement
