Repository liquibase/liquibase-test-harness, pull requests merged in 2025-04, with the labels that each got.

#1025 DAT-19656 - Filter out 'alter session set jdbc_query_result_format = …
  src/main/groovy/liquibase/harness/data/ChangeDataTests.groovy
  src/main/groovy/liquibase/harness/util/TestUtils.groovy
  src/main/resources/liquibase/harness/data/expectedResultSet/informix/loadData.json
Labels: TypeBug

#1027 DAT-19863 add PKI authentication by default for snowflake test harness flows.
  .github/workflows/snowflake.yml
Labels: TypeEnhancement

#1010 🔧 chore: update GitHub Actions and Docker images to latest versions
  .github/workflows/main.yml
Labels: skipReleaseNotes

#1033 INT-141. added GCP Postgres 15 & 16 to the CI/CD
  .github/workflows/gcp.yml
Labels: TypeEnhancement

#1036 INT-122. removed Oracle 21c support
  .github/workflows/OracleRunParallel.yml
  src/test/resources/docker/oracle-xe/docker-compose.yml
  src/test/resources/harness-config.yml
Labels: skipReleaseNotes

#1044 DAT-20080 DevOps :: Migrate legacy LocalStack API keys to new Auth Tokens
  .github/workflows/aws.yml
  README.localstack.md
Labels: sdou, skipReleaseNotes
